### ISSUE TITLE
Performance contract - Data set have invalid dimension

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#99] opened 2016-06-22 20:00 UTC
An error message is displayed when selecting a data set:
Same issue in demo & dev

![image](https://cloud.githubusercontent.com/assets/8737709/16281428/b1ad4364-38c4-11e6-9c8d-42a064619846.png)

**Comment by abyot** [comment] 2016-06-25 10:00
This is not a bug, rather an invalid meta-data configuration. Please make sure the selected data set has its Baseline property set to "Yes".

Also, make sure all the data elements assigned to this data set have a category combination no other than "Baseline, Target and Progress". This part is very important. We have agreed to use only "baseline, target and progress" dimension.

**Comment by Aleglise** [comment] 2016-06-26 07:19
Thank you.
I agree. Baseline data set should be flaged as a "Baseline type" through the Baseline attribute. 

We have agreed to use only "baseline, target and progress" dimension and also "Budget type" and "Budget source" for project's budget data elements.

@arunimam please acknowledge our comments and close this issue if you do not have question about it.

**Comment by arunimam** [comment] 2016-06-28 17:22
The datasets

Baseline (OC) Export Value Chains Traditional & Non traditional District Level Quarterly Dataset
Target (OC) Export Value Chains Traditional & Non traditional District Level Quarterly Dataset
Progress (OC) Export Value Chains Traditional & Non traditional District Level Quarterly Dataset

We modified these datasets on the latest requirements of assigning only one cat combo of B/T/P but after assigning the dataset to orgunit we are getting an exception error in data entry screen 

We tried recreating the datasets with newly created data elements, but unfortunately still facing same exception error

![image](https://cloud.githubusercontent.com/assets/12066960/16425559/f57a63e8-3d82-11e6-8660-26c9e098ca2e.png)

Requesting Abyot to look into the matter

**Closed as completed** 2016-08-12 11:15 UTC
Labels: bug
