### ISSUE TITLE
the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by Aleglise** [minagri-rwanda/DHIS2-Agriculture#45] opened 2016-05-04 14:45 UTC
When creating a data element I have a message saying that "Object already exists" whereas the object doesn't exist.

in console I have the following error

> Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by abyot** [comment] 2016-05-15 05:50
Are you still getting this?

**Comment by Aleglise** [comment] 2016-05-16 08:58
No. Any idea about the source of this issue (which led to project creation impossibility)?

**Comment by abyot** [comment] 2016-06-03 15:15
I am not able to reproduce this and closing...

**Closed as completed by abyot** 2016-06-03 15:15 UTC
Labels: bug
